// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvwbqnhkdtuguuzsaqwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2d2JxbmhrZHR1Z3V1enNhcXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzcxMDQsImV4cCI6MjA3MDY1MzEwNH0.If-mbcOCRijH9zuR74YSSik6L4DiNxbHqKsZUI39odg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});